<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Static\Images\bg_auth.jpg" />
    <None Remove="Static\Images\DM.png" />
    <None Remove="Static\Images\home_button_image.png" />
    <None Remove="Static\Images\idle.png" />
    <None Remove="Static\Images\invisible.png" />
    <None Remove="Static\Images\online.png" />
    <None Remove="Static\Images\plus.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Static\Images\DM.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Static\Images\DND.png" />
    <Resource Include="Static\Images\idle.png" />
    <Resource Include="Static\Images\invisible.png" />
    <Resource Include="Static\Images\online.png" />
    <Resource Include="Static\Images\logoutlogo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Static\Images\bg_auth.jpg" />
    <Resource Include="Static\Images\home_button_image.png" />
    <Resource Include="Static\Images\plus.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.25" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="ViewModels\Base\" />
  </ItemGroup>

</Project>
